name: matrix
description: Pro realistic hacking process.
version: 0.0.1

environment:
  sdk: ^3.4.3

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0